project_id = "ygxyiperkzwobexaphsa"

[functions.generate-ai-brief]
verify_jwt = false

[functions.ai-agent-chat]
verify_jwt = false

[functions.coach-evaluate]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp-login]
verify_jwt = false
